#pragma once
#include <ntddk.h>

#define IOCTL_PING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PHYS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _PHYS_READ_REQUEST
{
    ULONGLONG PhysicalAddress;
    ULONG Size;
} PHYS_READ_REQUEST;
